### ISSUE TITLE
Mobile view: Get in Touch not responsive 

### ISSUE THREAD

**Issue by Mridul07Sharma** [heyimShivam/Robotics-Website#63]
![Screenshot_2022-08-28-13-35-43-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/91523026/187064346-e47842e4-a541-4a77-b406-81466b28bce0.jpg)

**Comment by heyimShivam** [comment]
@ArjunThakur543 PTAL

**Comment by heyimShivam** [comment]
this has been addressed PTAL

**Comment by Mridul07Sharma** [comment]
Margin is not uniform and the send button is not center aligned

![Screenshot_2022-08-28-22-25-03-67_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/91523026/187678981-ef6af0a0-1425-46a4-843c-beec0c33fd98.jpg)
